# Generated by Django 4.0.4 on 2022-04-12 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
    ]
