# Generated by Django 4.0.4 on 2022-04-12 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_auto_20220412_1222'),
    ]

    operations = [
    ]
