# Generated by Django 4.0.4 on 2022-04-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0003_auto_20220412_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
