# Generated by Django 4.0.4 on 2022-04-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0006_rename_domain_creation_date_domain_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='creation_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='expiration_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='name_servers',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='registrant_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
